---
version: 2
build:
  image: ghcr.io/henrywinterbottom-noaa/ubuntu20.04.ufs_pyutils
#  os: ubuntu-20.04
#  tools:
#    python: "3.9"
  apt_packages:
    - gfortran
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
    - requirements: docs/source/requirements.txt
