---
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
    - gfortran
  set_env:
    - PYTHONPATH: /home/ufs_pyutils/sorc
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
    - requirements: docs/source/requirements.txt
    - requirements: requirements.txt
    - requirements: git+https://github.com/HenryWinterbottom-NOAA/ufs_pyutils.git@develop /home/

