---
version: 3
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  before_build:
    - apt-get update && apt-get install -y
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
    - requirements: docs/source/requirements.txt
