---
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
    - gfortran
requirements:
  - -e /home/packages
  - git+https://github.com/HenryWinterbottom-NOAA/ufs_pyutils.git@develop
env:
  global:
    - PYTHONPATH: /home/packages/ufs_pyutils/sorc
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
    - requirements: docs/source/requirements.txt
    - requirements: requirements.txt
