---
name: Build Tests
on:
  - push
  - pull_request
  - release
jobs:
  build:
    runs-on: ubuntu-latest
    name: Run the ufs_pyutils build-tests.
    steps:
      - name: Build and install Python dependencies.
        run: >
          $(command -v wget) --no-check-certificate
          https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh

          $(command -v sh) Miniconda3-py39_4.10.3-Linux-x86_64.sh -b -p miniconda

          $(command -v python) -m pip install --upgrade pip
      - name: Checkout ufs_pyutils.
        uses: actions/checkout@v2
        with:
          path: ufs_pyutils
      - name: Build ufs_pyutils.
        run: >
          cd "${GITHUB_WORKSPACE}/ufs_pyutils/"

          $(command -v python) "${GITHUB_WORKSPACE}/ufs_pyutils/setup.py" build

          $(command -v python) "${GITHUB_WORKSPACE}/ufs_pyutils/setup.py" install --user
